<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-8TP6OQIJ" failures="1" tests="3" name="Test" time="12.769" errors="0" timestamp="2023-11-21T07:45:42 IST">
  <testcase classname="testcases.RegisterTestCases" name="verifyRegisterationWithInBlankData" time="2.595"/>
  <testcase classname="testcases.RegisterTestCases" name="verifyRegisterationWithValidData" time="2.987">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://naveenautomationlabs.com/opencart/index.php?route=account/success] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/register]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://naveenautomationlabs.com/opencart/index.php?route=account/success] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/register]
at com.Resources.commonMethods.handleAssertions(commonMethods.java:18)
at testcases.RegisterTestCases.verifyRegisterationWithValidData(RegisterTestCases.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyRegisterationWithValidData -->
  <testcase classname="testcases.LoignTestCases" name="validLoginTest" time="0.712"/>
</testsuite> <!-- Test -->
